/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SESI_SENAI
 */
public class MeuJogos extends javax.swing.JFrame {

    /**
     * Creates new form MeuJogos
     */
    public MeuJogos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogo2 = new javax.swing.JButton();
        jogo3 = new javax.swing.JButton();
        jogo1 = new javax.swing.JButton();
        jogo5 = new javax.swing.JButton();
        jogo6 = new javax.swing.JButton();
        jogo4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        imgfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jogo2.setBackground(new java.awt.Color(153, 0, 0));
        jogo2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jogo2.setForeground(new java.awt.Color(255, 255, 255));
        jogo2.setText("Baccarat");
        jogo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogo2ActionPerformed(evt);
            }
        });
        getContentPane().add(jogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 170, 50));

        jogo3.setBackground(new java.awt.Color(153, 0, 0));
        jogo3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jogo3.setForeground(new java.awt.Color(255, 255, 255));
        jogo3.setText("Caça-niqueis");
        jogo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogo3ActionPerformed(evt);
            }
        });
        getContentPane().add(jogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 170, 50));

        jogo1.setBackground(new java.awt.Color(153, 0, 0));
        jogo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jogo1.setForeground(new java.awt.Color(255, 255, 255));
        jogo1.setText("Blackjack");
        jogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 170, 50));

        jogo5.setBackground(new java.awt.Color(153, 0, 0));
        jogo5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jogo5.setForeground(new java.awt.Color(255, 255, 255));
        jogo5.setText("Roleta");
        jogo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogo5ActionPerformed(evt);
            }
        });
        getContentPane().add(jogo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 170, 50));

        jogo6.setBackground(new java.awt.Color(153, 0, 0));
        jogo6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jogo6.setForeground(new java.awt.Color(255, 255, 255));
        jogo6.setText("Sic Bo");
        jogo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogo6ActionPerformed(evt);
            }
        });
        getContentPane().add(jogo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 170, 50));

        jogo4.setBackground(new java.awt.Color(153, 0, 0));
        jogo4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jogo4.setForeground(new java.awt.Color(255, 255, 255));
        jogo4.setText("poker");
        jogo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogo4ActionPerformed(evt);
            }
        });
        getContentPane().add(jogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 170, 50));

        jLabel1.setFont(new java.awt.Font("Vineta BT", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     Cassino El Chapo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 700, 60));

        jLabel6.setFont(new java.awt.Font("Vineta BT", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("     Cassino El Chapo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 700, 52));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Selecione o Jogo ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 104, 170, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Selecione o Jogo ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 170, -1));

        imgfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundocassino.jpg"))); // NOI18N
        imgfundo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                imgfundoFocusGained(evt);
            }
        });
        getContentPane().add(imgfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogo2ActionPerformed
        Baccarat baccarat = new Baccarat();
        baccarat.setVisible(true);
    }//GEN-LAST:event_jogo2ActionPerformed

    private void jogo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogo3ActionPerformed
        Cacaniqueis cacaniqueis = new Cacaniqueis();
        cacaniqueis.setVisible(true);
    }//GEN-LAST:event_jogo3ActionPerformed

    private void jogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogo1ActionPerformed
      BlackJack blackjack = new BlackJack();
      blackjack.setVisible(true);
    }//GEN-LAST:event_jogo1ActionPerformed

    private void jogo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogo5ActionPerformed
        Roleta roleta = new Roleta();
        roleta.setVisible(true);
    }//GEN-LAST:event_jogo5ActionPerformed

    private void jogo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jogo6ActionPerformed

    private void jogo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jogo4ActionPerformed

    private void imgfundoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imgfundoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_imgfundoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeuJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeuJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeuJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeuJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeuJogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgfundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jogo1;
    private javax.swing.JButton jogo2;
    private javax.swing.JButton jogo3;
    private javax.swing.JButton jogo4;
    private javax.swing.JButton jogo5;
    private javax.swing.JButton jogo6;
    // End of variables declaration//GEN-END:variables
}
