
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SESI_SENAI
 */
public class Roleta extends javax.swing.JFrame {

    public Roleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numeroApostado = new javax.swing.JTextField();
        campoTexto = new javax.swing.JTextField();
        jogar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sorteado = new javax.swing.JLabel();
        fundocassino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vineta BT", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Roleta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 60));

        jLabel6.setFont(new java.awt.Font("Vineta BT", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Roleta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 700, 52));

        numeroApostado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroApostadovalorEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(numeroApostado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 220, 30));

        campoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextovalorEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(campoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 220, 30));

        jogar.setFont(new java.awt.Font("Vineta BT", 2, 14)); // NOI18N
        jogar.setForeground(new java.awt.Color(153, 0, 0));
        jogar.setText("JOGAR");
        jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarActionPerformed(evt);
            }
        });
        getContentPane().add(jogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 180, 36));

        jLabel5.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*Número de 0 á 36*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 110, 20));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor da aposta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 170, 30));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel10.setText("Valor da aposta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 170, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número á apostar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 180, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel7.setText("Número á apostar:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 180, -1));

        sorteado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        sorteado.setForeground(new java.awt.Color(255, 255, 255));
        sorteado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(sorteado, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 390, 710, -1));

        fundocassino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundocassino.jpg"))); // NOI18N
        getContentPane().add(fundocassino, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroApostadovalorEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroApostadovalorEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroApostadovalorEntradaActionPerformed

    private void campoTextovalorEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextovalorEntradaActionPerformed
      
    }//GEN-LAST:event_campoTextovalorEntradaActionPerformed

    private void jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarActionPerformed
        String aux = campoTexto.getText();
        int aposta = Integer.parseInt(aux);
        aux = numeroApostado.getText();
        int numApostaddo = Integer.parseInt(aux);
        Random i = new Random();
        int numSorteado = i.nextInt(36);
        if(numApostaddo == numSorteado){
             sorteado.setText("VOCÊ GANHOU!!!");
        }else {
            sorteado.setText("Não ganhou! \n\n O número sorteado é: " + numSorteado);
        }
    }//GEN-LAST:event_jogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Roleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Roleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Roleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Roleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Roleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTexto;
    private javax.swing.JLabel fundocassino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jogar;
    private javax.swing.JTextField numeroApostado;
    private javax.swing.JLabel sorteado;
    // End of variables declaration//GEN-END:variables
}


